// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package pb;

public interface ChatOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pb.Chat)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string content = 1;</code>
   */
  java.lang.String getContent();
  /**
   * <code>string content = 1;</code>
   */
  com.google.protobuf.ByteString
      getContentBytes();
}
