// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package pb;

public interface LogoutOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pb.Logout)
    com.google.protobuf.MessageOrBuilder {
}
