// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package pb;

/**
 * Protobuf enum {@code pb.MessageType}
 */
public enum MessageType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>OK = 0;</code>
   */
  OK(0),
  /**
   * <code>PING = 1;</code>
   */
  PING(1),
  /**
   * <code>PONG = 2;</code>
   */
  PONG(2),
  /**
   * <code>LOGIN = 3;</code>
   */
  LOGIN(3),
  /**
   * <code>LOGOUT = 4;</code>
   */
  LOGOUT(4),
  /**
   * <code>BROADCAST = 6;</code>
   */
  BROADCAST(6),
  /**
   * <code>CHAT = 7;</code>
   */
  CHAT(7),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>OK = 0;</code>
   */
  public static final int OK_VALUE = 0;
  /**
   * <code>PING = 1;</code>
   */
  public static final int PING_VALUE = 1;
  /**
   * <code>PONG = 2;</code>
   */
  public static final int PONG_VALUE = 2;
  /**
   * <code>LOGIN = 3;</code>
   */
  public static final int LOGIN_VALUE = 3;
  /**
   * <code>LOGOUT = 4;</code>
   */
  public static final int LOGOUT_VALUE = 4;
  /**
   * <code>BROADCAST = 6;</code>
   */
  public static final int BROADCAST_VALUE = 6;
  /**
   * <code>CHAT = 7;</code>
   */
  public static final int CHAT_VALUE = 7;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static MessageType valueOf(int value) {
    return forNumber(value);
  }

  public static MessageType forNumber(int value) {
    switch (value) {
      case 0: return OK;
      case 1: return PING;
      case 2: return PONG;
      case 3: return LOGIN;
      case 4: return LOGOUT;
      case 6: return BROADCAST;
      case 7: return CHAT;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      MessageType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
          public MessageType findValueByNumber(int number) {
            return MessageType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return pb.Message.getDescriptor().getEnumTypes().get(0);
  }

  private static final MessageType[] VALUES = values();

  public static MessageType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private MessageType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:pb.MessageType)
}

