// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package pb;

public final class Message {
  private Message() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_Ping_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_Ping_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_Pong_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_Pong_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_Login_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_Login_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_Logout_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_Logout_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_Chat_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_Chat_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_Broadcast_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_Broadcast_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rmessage.proto\022\002pb\"\006\n\004Ping\"\006\n\004Pong\"\025\n\005L" +
      "ogin\022\014\n\004name\030\001 \001(\t\"\010\n\006Logout\"\027\n\004Chat\022\017\n\007" +
      "content\030\001 \001(\t\"\034\n\tBroadcast\022\017\n\007content\030\001 " +
      "\001(\t*Y\n\013MessageType\022\006\n\002OK\020\000\022\010\n\004PING\020\001\022\010\n\004" +
      "PONG\020\002\022\t\n\005LOGIN\020\003\022\n\n\006LOGOUT\020\004\022\r\n\tBROADCA" +
      "ST\020\006\022\010\n\004CHAT\020\007B\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_pb_Ping_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_pb_Ping_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_Ping_descriptor,
        new java.lang.String[] { });
    internal_static_pb_Pong_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_pb_Pong_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_Pong_descriptor,
        new java.lang.String[] { });
    internal_static_pb_Login_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_pb_Login_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_Login_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_pb_Logout_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_pb_Logout_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_Logout_descriptor,
        new java.lang.String[] { });
    internal_static_pb_Chat_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_pb_Chat_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_Chat_descriptor,
        new java.lang.String[] { "Content", });
    internal_static_pb_Broadcast_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_pb_Broadcast_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_Broadcast_descriptor,
        new java.lang.String[] { "Content", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
