// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package pb;

public interface PingOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pb.Ping)
    com.google.protobuf.MessageOrBuilder {
}
