// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package pb;

public interface PongOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pb.Pong)
    com.google.protobuf.MessageOrBuilder {
}
